// Speech recognition for the falling-symbol game.
// zh-TW ASR returns Chinese characters, not bopomofo — saying「ㄅ」comes back
// as 波/撥/伯…, so each symbol carries a tone-insensitive homophone accept-list.

const SR = typeof window !== "undefined"
  ? (window.SpeechRecognition || window.webkitSpeechRecognition)
  : null;

export function isRecognitionSupported() {
  return !!SR;
}

// Homophones of each symbol's canonical isolated reading (any tone).
// Generated by tools/gen_accept.py from Unihan kMandarin/kHanyuPinlu
// readings (common modern readings only — kHanyuPinyin is skipped because
// its obsolete literary readings would accept wrong answers), filtered to
// Big5-encodable characters, unioned with the original hand-picked lists.
const ACCEPT_CHARS = {
  b: "波撥玻剝菠播伯博勃薄泊帛柏箔搏膊亳僠僰卜哱啵嚗嶓帗懪挬擘檗欂浡渤犦猼瓝瓟砵碆礡簙簸糪缽胉脖舶葧蔔蕃蘗袚袹襏襮譒豰跛踣蹳郣鈸鉑鋍鎛鑮餑餺馞駁駮髆鱍鵓",
  p: "坡潑婆迫破頗魄粕叵剖岥岶昢桲櫇泊烞珀皤笸蒪謈鄱醱釙鏺",
  m: "摸模膜磨魔抹末沒莫墨默摩茉陌漠寞万劘嗼塻妺嫫摹暯枺歾歿沫瀎爅瘼眽瞙秣粖糢纆莈藦蘑蛨蟔謨貊貘銆鏌靺饃驀髍",
  f: "佛坲",
  d: "得德的地嘚淂",
  t: "特忑忒慝蟘貣鋱",
  n: "呢訥哪吶眲",
  l: "樂勒了肋垃叻仂扐氻泐砳竻阞鰳",
  g: "哥歌戈鴿格閣革各個割葛隔咯胳仡佮哿嗝圪塥愅挌搿擱滆滒犵獦疙硌箇肐膈舸茖虼袼觡輵轕鉻閤鞈鞷韐騔骼鬲鮯鴐",
  k: "科顆棵柯咳蝌殼可克刻課客苛剋勀匼嗑坷堁岢嵑嵙嶱恪搕敤榼樖氪渴溘牁犐珂瞌砢磕稞窠緙翗艐薖趷軻鈳騍髁",
  h: "喝荷河何合和賀鶴盒核呵嚇佫劾嗃壑姀峆敆曷楁欱毼涸渮澕煂熆熇盉盍礉禾篕籺紇翮翯菏蚵螛褐覈訶謞赫郃鉌鑉闔鞨頜魺鶡麧齕龢",
  j: "機雞基積擊肌姬即急集級極幾己擠脊計記濟繼寄季技既紀寂丌丮乩亟伋伎佶偈偮冀几刉剞劑勣及吉咭唧嘰嚌圾堲塈塉墼妀妓姞嫉屐岌嵇嶯庴彶徛忌忣悸惎懻戟戢掎揤撠敧旡暨暩机极枅棘楫槉橶檕櫅殛毄汲泲洎湒漃漈潗激濈瀱犄狤璣畸畿疾痵瘠癠癪磯祭禨稘稷稽穄穊穖穧笄笈箕簊籍系紒給緝績罽羇羈耤膌臮芨芰茍茤蒺蓻蔇蕀蕺薊薺藉蘮蘻虀虮螏蟣裚襋覬觙觭誋諅譏谻趌跡跽踖蹐蹟躋躤輯轚鄿銈銡錤鏶鐖鑇際隮霵霽鞿飢饑驥髻鬾魕鯚鰶鰿鱀鱭鵋鶺鷑鸄麂齌齎齏",
  q: "七期欺漆淒戚齊其奇騎旗棋起豈企氣器汽棄泣妻砌乞亓俟倛僛凄呇咠唭啟嘁圻埼契娸婍屺岐岓崎忔忯悽慼憩懠掑攲旂杞柒栔栖桼棨棲榿槭欹歧气汔沏淇湆湇濝玂琦琪甈畦疧盵碕磧磩祁祇祈祺綦綺緀罊耆肵臍艩芑芞萁萋葺藄蘄蚑蚔蚚蛣蜞蟿蠐訖諆諿跂踑蹊軝迄迉邔郪釮錡鏚霋頎騏騹鬐鬿魌鯕鰭鵸鶀鶈麒麡鼜",
  x: "西希吸昔析息習席洗喜戲系細膝溪嘻夕犀錫係俙傒僖兮凞卌呬咥唏囍奚媳嬉屖屣屭嶍嶲巇徆徙徯忥怬恄恓悉悕惁惜慀扱晞晰曦枲桸榽槢樨橀檄欯欷歖氥汐浠淅滊漇潝潟烯焟熂熄熙熹燨爔犧狶琋璽瘜皙盻睎矽硒磎礂禊禧稀穸窸粞綌緆縰繫羲翕肸舄莃菥葸蒠蓆蓰蕮薂虩蜥螅螇蟋蟢蠵衋襲覡覤觿諰謑謵譆谿豨豯貕赩蹝郋郗郤鄎酅醯釐釳釸鎴鑴闟隙隰雟霫飁餼騱騽驨鬩鰼鵗鸂黖鼷",
  zh: "之知支芝隻織汁直值植執侄指紙只止至志致智製治秩擲質乿偫傂制卮厔吱咫址坁埴墆姪嬂寘峙帙幟庢庤廌彘徵忮恉慹懥懫戠扺扻挃搘摭摯擳旨晊枝枳柣桎梔椥楖榰樴櫍櫛殖汥汦沚泜洷淔淽滍滯瀄炙犆狾猘瓡畤疐疻痔痣礩祉祑祗禔秖秪秷稙稚窒紩緻縶置翐職肢胑胝脂膣膱臸芷藢蘵蛭蜘螲蟙衹衼袟覟觶誌豸贄趾跖跱蹠躑躓軹輊迣郅酯銍鋕鑕阤阯陟雉馽駤騭騺鳷鴙鷙黹",
  ch: "吃痴持池遲尺齒赤翅斥匙馳恥侈傺叱呎哧啻喫嗤墀媸弛彳懘抶摛攡敕欼歭湁漦熾瓻痸瘈瘛癡眵瞝笞箎篪絺翨胣胵茌荎蚇蚩蚳螭袲褫誺謘豉貾趍跮踟遫鉓鉹飭饎魑鴟鶒鷘麶黐齝",
  sh: "詩施師獅失十時實食石識史使始是事市式室視試世勢士仕似侍匙嗜噬塒奭姼媞寔尸屍屎崼弒徥忕恀恃戺拭拾揓柿栻榯氏湜湤溡溮溼澨濕烒矢示祏筮簭絁舐葹蒔蓍虱蝕蝨螫褷襫襹觢誓諟諡謚豕貰軾适逝適遾邿釋鈰鉈鉐鉽銴飾駛鰣鰤鳲鶳鼫鼭",
  r: "日鈤馹",
  z: "資姿滋茲吱子紫仔字自倳剚吇呰咨姊孜孳崰嵫恣杍栥梓椔淄滓漬澬牸玆璾眥矷秭秶笫籽粢紎緇耔胏胔胾芓蓻觜訾訿諮貲趑輜鄑釨鈭錙鎡髭鯔鶅鼒齍",
  c: "疵慈磁瓷詞辭此次刺賜雌伺佌佽偨呲嬨庛朿柌栨泚濨玼皉祠絘縒茈茦茨莿薋蛓蠀趀跐飺餈骴髊鮆鶿齹",
  s: "思斯私司絲撕死四寺似飼嘶俬儩兕凘嗣姒巳廝柶楒榹汜泀泗洍涘澌磃祀禗禠笥緦罳耜肂肆蕬蕼虒蜤螄蟴覗貄鈶鉰颸駟鷥鼶",
  a: "啊阿呵錒",
  o: "喔哦噢",
  e: "額俄餓鵝惡厄婀匎吪呃咢哦噁噩囮堊堨堮姶娥屙岋峉峨崿廅愕扼搤搹枙櫮歞涐珴痾皒睋砐砨莪萼蚅蛾蝁訛詻諤豟軛軶迗遏遻鄂鋨鍔鑩閼阨頞顎餩魤鱷鶚齃齶",
  "ê": "欸誒耶爺也夜葉椰野冶咽噎埜嶪抴捙掖揶擛擨擫暍曄曳業歋殗液漜澲燁瞱腋蠮謁鄴鍱鎑鐷靨頁饁",
  ai: "愛哀埃挨矮癌艾唉僾哎啀嗌噯壒娭娾嬡捱敳昹曖欸毐溰溾濭璦皚礙薆藹譪譺鑀閡隘靄靉餲騃鴱",
  ei: "欸誒",
  ao: "凹熬襖傲奧澳懊嗷坳墺奡媼岰嶴廒扷拗摮擙敖柪滶爊獒璈磝翱聱芺蔜薁螯謷遨鏊鏖镺隞隩驁鰲鼇",
  ou: "歐偶嘔鷗毆藕吘慪櫙漚熰甌耦腢蕅藲謳鏂齵",
  an: "安按暗案鞍岸侒俺儑唵啽垵婩媕峖庵晻桉氨洝犴玵痷盦胺腤荌菴萻諳豻銨錌闇雸韽馣鵪黯",
  en: "恩嗯摁奀峎",
  ang: "骯昂盎卬肮醠",
  eng: "鞥嗯",
  er: "而兒耳爾二餌侕儿刵咡唲尒峏栭栮樲毦洏洱珥聏胹荋薾衈貳輀邇鉺陑駬鮞鴯",
  i: "一衣依醫以椅乙意義易益移姨壹乂亄亦伊伿佁佚佾侇俋倚偯儀億刈劓劮勩匜咦咿唈噫囈圛圯垼埶埸墿夷奕媐嫕嫛宜宧寱寲屹峓崺嶧嶬嶷已帟帠廙异弈弋彝役怡恞悒憶懌懿扆抑拸挹掜揖敼斁旖晹暆曀杙枍枻柂栘栺桋椸槸檍檥檹欥欭殔殪毅毉沂沶泆洢浂浥溢漪潩澺瀷焲熠熤熪熼燚燡燱狋猗玴珆瑿瓵異疑疫痍瘞瘱眙睪矣礒禕稦箷簃縊繄繶繹羛羠羿翊翌翳翼耛耴肄肊胰膉臆艗艤芅苡萓蓺薏藙藝蘙蛜蛦蜴螔螘蟻衪衵袘裔裛襼觺訑詍詑詒詣誃誼謻譯議豷貤貽賹贀跇跠踦軼轙迆迤迻逸遺邑郼酏醳醷釔釴鉯銥鎰鏔鐿陭隿霬靾頤顊顗飴饐驛鮨鳦鶂鷁鷊鷖鷾鸃黓黟黳齮齸",
  u: "屋烏污巫無五午舞武物霧誤悟吳仵伍侮俉倵兀剭務勿卼吾唔啎嗚嘸圬塢婺嫵寤屼岉峿嵨廡忤惡憮戊扤捂摀晤杇杌梧橆歍毋汙洖洿浯潕焐牾玝珸甒痦矹碔窏粅芴莁蕪蘁蜈螐誣譕躌迕逜郚鄔鋈鎢阢雺靰騖鯃鴮鵡鶩鷡鼯齀",
  "ü": "淤迂魚漁於余雨語玉遇育浴娛与予于俁俞偊傴儥吁唹喻噊噳圄圉域堉堣堬妤嫗宇寓寙峪崳嵎嶼庾彧御悆愈愉愚慾戫扜揄敔斔斞旟昱杅棜棫楀楰榆欲歈歟歶毓淢淯渝湡潏澞澦灪煜燏燠爩牏狳獄玗瑀瑜璵畬瘀瘉瘐癒盂盓睮矞砡硢礜祤禦禹禺稢穻窬窳竽箊篽籅籲紆緎繘罭羭羽聿腴臾舁與艅芋萭萸蒮蓹蕍蕷薁蘌蘛虞蜮蝓螸衧袬裕褕覦諛諭謣譽豫貐踰軉輍輿轝逾遹邘郁鄅醧鈺鋊鋙錥閾陓隅雓雩預頨飫餘饇馭驈鬱鬻魊鮽鰅鱊鳿鴥鵒鷸鸆鸒麌齬",
  ia: "牙呀鴨壓芽雅亞崖丫伢厊啞圔圠埡堐婭孲岈庌押掗揠枒椏氬涯犽猰玡琊睚砑窫聐蕥蚜衙襾訝軋迓錏鴉齖齾",
  io: "唷喲",
  ie: "耶爺也夜葉椰野業頁冶咽噎埜嶪抴捙掖揶擛擨擫暍曄曳歋殗液漜澲燁瞱腋蠮謁鄴鍱鎑鐷靨饁",
  ian: "煙鹽眼演燕嚥言顏延岩偃偣傿儼兗匽厭厴咽唁喭噞嚴堰壛壧奄妍姲娮嫣嬮嬿孍宴崦嵃嵒巖巘弇彥愝懨戭扊抁掞掩揅揜敥晏曣曮棪椻椼楌檐沇沿淊淹渰湮溎漹灩炎烻焉焰焱燄爓牪狿猒珚琰甗研硯碞礹筵簷綖縯罨胭腌臙艷芫莚菸萒虤蜒蝘衍裺褗觾諺讌讞豔贗躽郔郾鄢酀酓醃醼釅閆閹閻隒雁顩饜騴驗驠鬳魘鰋鴈鴳鶠鷃鷰黤黫黭黶鼴齞齴龑",
  in: "因音陰銀引飲印隱冘凐吟喑噾嚚圁垔垠垽堙堷夤姻婬寅尹崟廕愔慇憖朄檃檭歅殥殷氤洇淫湚濦烎狺猌瘖癮硍禋窨粌絪胤苂茵荶蒑蔩蔭蘟蚓螾蟫裀誾諲讔趛輑鄞酳鈏銦闉霒霠霪靷韾駰鷣齗",
  iang: "央羊陽楊養癢樣氧洋仰佒佯坱垟姎岟崵崸徉怏恙懩抰揚攁昜暘柍殃泱漾瀁炴烊煬珜痒瘍眻禓秧紻羕胦蛘蝆軮鉠鍚鐊雵鞅颺鴦鸉",
  ing: "英鷹迎營影硬應嬰螢偀嚶塋媵嫈嬴廮摬攍攖映朠梬楹櫻浧渶潁濴瀅瀛瀠瀯瀴煐熒瑛瑩瓔甇甖癭盈矨碤礯穎籯縈纓罃罌膺藀蘡蝧蠅蠳褮覮謍譻賏贏郢鎣霙韺鱦鶧鶯鸚",
  iou: "優悠油由游友有右幼柚郵优佑侑偤卣又呦嚘囿姷宥尤峟幽庮怮憂懮攸斿栯楢槱櫌沋泑浟瀀牖牰狖猶猷疣祐秞纋羑耰聈苃莠蒏蕕蚰蚴蝣訧誘貁輶迶逌遊鄾酉釉鈾銪魷麀黝鼬",
  ua: "挖蛙娃瓦襪哇佤嗢媧洼溛漥穵窊窪膃",
  uo: "窩我臥握渦蝸沃斡仴倭偓婐幄捰撾擭涴渥濣焥猧瓁瞃硪腛臒萵踒雘齷",
  uai: "歪外喎崴",
  uei: "威微為圍偉尾未味位胃衛偎亹偽儰危唯喂喡囗圩壝委娓媦寪尉峗峞崣嵬巍帷幃廆徫惟愄慰揋撱斖暐桅椲椳欈洈洧浘渨渭湋溈溦潿濰濻瀢烓煒煟煨燰犚犩猥瑋畏痏痿癓硊碨磈磑維緯罻腲艉芛菋萎葦葨葳蒍蓶蔚薇薳藯蘶蜲蜼蝛蝟褽覣覹詴諉謂讆踓躗逶違鄬醀鍏鍡鏏闈隇隈隗霨霺韋韙韡頠餧餵饖骫魏鮇鮠鮪",
  uan: "彎灣玩完晚碗萬丸頑万倇刓剜卍婉婠宛岏忨惋抏挽捖捥晥晼汍潫澫烷琬畹皖睕瞣紈綩綰翫脕脘腕芄菀薍蜿蟃豌踠輐輓鋄",
  uen: "溫文聞穩問紋蚊吻刎呡塭妏抆搵桽殟汶炆玟璺瘟紊芠豱轀閺閿闅雯顐駇魰鳼鼤",
  uang: "汪王往網忘望旺亡妄尢尪惘暀朢枉瀇盳网罔莣菵輞迋魍",
  ueng: "翁嗡甕塕暡滃瓮瞈罋聬蓊蕹螉鶲齆",
  yue: "約月越樂閱悅躍岳刖嶽戉抈曰樾瀹爚玥矱礿禴箹籥粵蘥蚎軏鈅鉞鸑鸙黦龠",
  yuan: "冤圓園元原遠院願員猿噮垣垸夗妧妴媛媴嫄嬽怨悁惌愿掾援杬棩榞榬櫞沅淵湲源溒灁爰獂瑗眢禐笎緣羱肙苑葾蒝蒬蚖蜎蜵蝝蝯螈袁裫裷褑謜轅邍邧鋺鎱駌騵鳶鴛鵷鶢黿鼘",
  yun: "暈雲勻允運韻云伝奫妘孕惲慍抎昀枟殞氳沄溳澐熅熉熨狁畇眃筠篔紜緷縕縜耘芸荺蕓薀蘊蝹褞賱贇鄆鄖醞鈗鋆阭隕霣韗韞頵餫馧馻齫",
  yung: "用永泳勇擁庸湧傭佣俑傛喁嗈噰埇塎墉壅嫞嵱廱恿悀慵揘槦涌滽澭灉甬癰禜臃蛹詠踊踴邕郺鄘醟鏞雍雝顒饔鰫鷛",
  ba: "八爸巴拔把霸疤芭仈叭吧壩峇弝扒捌朳柭灞犮癹矲笆粑罷耙胈茇菝蚆詙豝跁跋軷鈀靶魃鼥",
  ma: "媽麻馬罵嗎螞傌嘛嘜嬤孖抹榪溤犘瑪痲碼礣禡蟆鎷鬕鷌",
  da: "搭答達打大匒呾咑嗒噠妲怛撘汏沓炟畣瘩笚笪繨羍耷荅薘褡躂迖鎉鎝鐽靼韃龘",
  tu: "突圖徒土吐兔塗禿凸唋堍屠峹嵞嶀廜怢悇捈捸梌涂涋湥潳瘏稌筡腯荼菟葖蒤跿途酴釷鍎駼鵌鵚鵵鶟鷋鷵鼵",
  gou: "勾溝狗夠購鉤佝冓垢姤媾岣彀搆构枸構笱篝簼緱耇芶苟茩蚼袧覯詬遘雊韝",
  hua: "花華滑化話畫嘩划劃姡嫿嬅崋搳摦杹槬樺澅猾砉繣蘤螖觟諙譁釪釫鋘錵鏵驊鷨",
  mi: "咪迷米密蜜瞇謎冞冪嘧塓宓峚幎幦弭彌攠敉榓汨沕泌渳滵漞濔瀰灖熐爢獼瓕眯祕禰秘糜糸縻羃羋葞蔝蔤蘼覓覛謐醚醾銤靡鸍麊麋麛鼏",
  shu: "書梳舒輸熟數樹叔鼠殊倏儵咰塾墅姝婌孰尌屬庶怷恕戍抒攄暑曙朮束杸樞橾殳毹沭淑漱潻澍焂瑹疏癙秫糬紓綀署腧菽蔬薯藷虪蜀術裋襡襩豎贖跾軗述鄃鉥鏣陎隃鮛鵨鶐鸀黍",
  jia: "家加佳夾假價架嘉甲价伽傢唊婽嫁岬幏徦恝戛扴抸斝枷梜椵榎檟毠泇浹犌猳玾珈痂瘕稼笳耞胛茄莢葭蛺袈袷裌豭貑賈跏跲迦郟鉀鉿鋏鎵頰駕鴶鵊麚",
  qiu: "秋丘球求邱俅唒囚坵媝崷巰恘梂楸殏毬泅煪犰璆盚糗紌絿緧莍萩蓲虯蚯蛷蝤蝵蟗蠤裘觓觩訄賕趥逑遒酋釚銶鞦鮂鯄鰍鰽鶖鼽",
  xing: "星興行型形醒姓猩侀倖刑垶娙婞幸性悻惺擤杏洐涬滎煋瑆硎箵腥荇莕蛵觲邢鈃鉶鋞陘騂",
  zhu: "豬珠竹煮主住助朱佇侏囑壴孎嵀拄斸杼柱柷株樦櫧櫫欘殶泏注洙渚瀦灟炷燭疰瘃眝矚砫硃祝祩窋竺笁筑箸築篫紵紸絑罜羜翥舳苧茱茿莇著蛀蛛蝫蠋蠩蠾袾註誅諸貯跓跦躅軴逐邾鉒銖鑄钃陼馵駐鮢鱁鴸麆麈",
  chuan: "川穿船傳串喘暷椽歂氚汌猭玔瑏舛舡荈賗踳輲遄釧鶨",
  shui: "水誰稅睡帨涗脽裞",
  niao: "鳥尿嫋嬝嬲蔦裊褭",
  mao: "貓毛帽冒茅兞冇卯堥媢懋旄昴枆楙毷氂泖渵犛瑁眊瞀矛罞耄芼茂茆萺蓩蝐蝥蟊袤貌貿軞鄚鄮酕鉚錨髦髳鶜",
};

// Canonical isolated reading in pinyin, in case ASR returns Latin text.
const ACCEPT_PINYIN = {
  b: "bo", p: "po", m: "mo", f: "fo",
  d: "de", t: "te", n: "ne", l: "le",
  g: "ge", k: "ke", h: "he",
  j: "ji", q: "qi", x: "xi",
  zh: "zhi", ch: "chi", sh: "shi", r: "ri",
  z: "zi", c: "ci", s: "si",
  a: "a", o: "o", e: "e", "ê": "ye",
  ai: "ai", ei: "ei", ao: "ao", ou: "ou",
  an: "an", en: "en", ang: "ang", eng: "eng", er: "er",
  i: "yi", u: "wu", "ü": "yu",
  ia: "ya", io: "yo", ie: "ye", ian: "yan", in: "yin",
  iang: "yang", ing: "ying", iou: "you",
  ua: "wa", uo: "wo", uai: "wai", uei: "wei",
  uan: "wan", uen: "wen", uang: "wang", ueng: "weng",
  yue: "yue", yuan: "yuan", yun: "yun", yung: "yong",
  ba: "ba", ma: "ma", da: "da", tu: "tu", gou: "gou", hua: "hua",
  mi: "mi", shu: "shu", jia: "jia", qiu: "qiu", xing: "xing",
  zhu: "zhu", chuan: "chuan", shui: "shui", niao: "niao", mao: "mao",
};

// True if any alternative transcript counts as a correct answer for `item`.
// Accepts: the symbol's sound (homophone chars), the raw bopomofo glyph,
// the example word, or the pinyin reading.
export function matchesSymbol(transcripts, item) {
  const accept = ACCEPT_CHARS[item.id] ?? "";
  const pinyin = ACCEPT_PINYIN[item.id] ?? "";

  for (const raw of transcripts) {
    // NFD + strip combining marks so tone-marked Latin ("bō") matches "bo"
    const clean = raw.toLowerCase().normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .replace(/[\s.,!?，。！？、'’]/g, "");
    if (!clean) continue;
    if (clean.includes(item.symbol)) return true;
    if (item.exampleWord && clean.includes(item.exampleWord)) return true;
    if (pinyin && clean.includes(pinyin)) return true;
    for (const ch of clean) {
      if (accept.includes(ch)) return true;
    }
  }
  return false;
}

// Thin wrapper: continuous zh-TW recognition with interim results and
// auto-restart (iOS Safari ends sessions frequently on its own).
export function createRecognizer({ onText, onStateChange, onDebug }) {
  if (!SR) return null;

  const rec = new SR();
  rec.lang = "zh-TW";
  rec.continuous = true;
  rec.interimResults = true;
  rec.maxAlternatives = 5;

  let active = false;
  const dbg = (msg) => onDebug?.(msg);

  rec.onstart = () => dbg("session start");
  rec.onaudiostart = () => dbg("audio start (mic delivering)");
  rec.onspeechstart = () => dbg("speech detected");
  rec.onspeechend = () => dbg("speech ended");

  rec.onresult = (e) => {
    const texts = [];
    for (let i = e.resultIndex; i < e.results.length; i++) {
      const res = e.results[i];
      for (let j = 0; j < res.length; j++) {
        const t = res[j].transcript.trim();
        if (t) texts.push(t);
      }
    }
    if (texts.length) onText(texts);
  };

  rec.onend = () => {
    if (active) {
      dbg("session end → restart");
      try { rec.start(); } catch { /* already started */ }
    } else {
      dbg("session end");
      onStateChange?.(false);
    }
  };

  rec.onerror = (e) => {
    dbg(`error: ${e.error}`);
    if (e.error === "not-allowed" || e.error === "service-not-allowed") {
      active = false;
      onStateChange?.(false, e.error);
    }
    // "no-speech" / "aborted" fall through to onend and auto-restart
  };

  return {
    start() {
      active = true;
      try { rec.start(); } catch { /* already started */ }
      onStateChange?.(true);
    },
    stop() {
      active = false;
      try { rec.stop(); } catch { /* not started */ }
    },
    get active() { return active; },
  };
}
